triggers:
   - name: fl-tg1
     type: trigger
     version:
       counter: 3
       
   - name: fl-tg2
     type: trigger
     version:
       counter: 3
       
   - name: fl-tg3
     type: trigger
     version:
       counter: 2
